---
title: 'Project 1: Wrangling, Exploration, Visualization'
author: "SDS322E"
date: ''
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
  pdf_document:
    toc: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, fig.align = "center", warning = F, message = F,
tidy=TRUE, tidy.opts=list(width.cutoff=60), R.options=list(max.print=100))
```

## Data Wrangling, Exploration, Visualization

### Emily Dunnahoe ekd489

#### Introduction 
Is bigfoot an alien? This is the riveting question that this wrangling, exploring, and visualizing activity is not going to answer. I will look at paranormal sightings across the US, according to "paratype", and season of sighting. I will consider the longitudes, latitudes, seasons, and states to eke out any possible meaning. Mostly, I hope to be entertained.

<<<<<<< HEAD
=======
Is bigfoot an alien? This is the riveting question that this wrangling, exploring, and visualizing activity is hoping to answer. Okay, not this question exactly, but I will look at whether there is correlation between paranormal sightings and particular regions in the US. To this end, I will consider the dates, longitudes, latitudes, cities, and states to eke out any possible meaning. 
>>>>>>> a8287905c51e6e169e7367ad521a171e2077fad4

```{R}
UFO_sightings<-read.csv("https://query.data.world/s/kt4hdqddosnopecjgfcm2j3qk3ixek", header=TRUE, stringsAsFactors=FALSE);
big_foot<-read.csv("https://query.data.world/s/72wj67foxle6ztzeirnbdz6kpomzag", header=TRUE, stringsAsFactors=FALSE);

```

#### Tidying: Reshaping

<<<<<<< HEAD
My data was already tidy. So, below is really just arbitrary pivoting. Because of the amount of variables present, I paired everything done is in the joining/merging section below to make reshaping feel more reasonable from my perspective.   

```{R}
library(tidyverse)
big_foot %>% 
  pivot_wider(names_from="classification", values_from="number")->big_foot
big_foot %>% 
  pivot_longer(27:29, names_to= "classification", values_to="number")->big_foot
=======
My data is already technically cleaned, except for column with an unneeded date_time. I will separate and remove the time aspect from the UFO_sightings data, before removing any unnecessary variables for both datasets for ease of joining later. Additionally, I coerced R to view the longitude and latitudes as numeric variables to allow for appropriate dplyr shenanigans. Due to the the size of my dataset, I decided to take a slice of 500 observations from each to make it more manageable. 

```{R}
library(tidyverse)
big_foot %>%
  select(-c(2,5,6,10:28)) %>% 
  add_column(paratype= "bigfoot") ->big_foot_clean
big_foot_clean %>% 
  na.omit() %>% 
  slice(1:500)->big_foot_clean

UFO_sightings %>% 
  separate("date_time", into=c("date", "NA"), sep="T")->UFO_sightings_clean

  as.numeric(as.character(UFO_sightings_clean$city_longitude))->longitude
  as.numeric(as.character(UFO_sightings_clean$city_latitude))->latitude 
UFO_sightings_clean %>% 
  add_column(paratype= "UFO")%>% 
  select(-c(5:11)) %>% 
  na.omit() %>% 
  slice(1:500)->UFO_sightings_clean 


>>>>>>> a8287905c51e6e169e7367ad521a171e2077fad4
```

    
#### Joining/Merging

```{R}
<<<<<<< HEAD
big_foot %>%
  select(-c(2,3,5,6,10:28)) %>% 
  add_column(paratype= "bigfoot") %>% 
  na.omit() %>% 
  slice(1:500)->bf_clean
bf_clean %>% 
  group_by(state) %>% 
  mutate(ID=cur_group_id())->bf_clean

UFO_sightings %>% 
  separate("date_time", into=c("date", "NA"), sep="T")->UFO_clean
as.numeric(as.character(UFO_clean$city_longitude))->longitude
as.numeric(as.character(UFO_clean$city_latitude))->latitude 
UFO_clean %>% 
  add_column(paratype= "UFO")%>%   
  na.omit() %>% 
  slice(1:500) %>% 
  select(-c(5:11))->UFO_clean
UFO_clean %>% 
  group_by(state) %>% 
  mutate(ID=cur_group_id())->UFO_clean

bf_clean %>% 
  full_join(UFO_clean, by=c("latitude"="city_latitude", "longitude"="city_longitude", "state"="state", "paratype"="paratype", "date"="date", "observed"="summary", "ID"="ID"))->big_clean_UFO

```

Due to peculiarities of my data or my level of expertise, I had to alter both data sets a bit to get a join that made sense. Above is all of the cleaning steps that happened before joining and my performative reshaping above. 

The column with an unneeded date_time was separated and the time aspect removed from the UFO_sightings data, before removing any unnecessary variables from both data sets for ease of joining later. This resulted in the removal of 21 variables of the original 28 in the big_foot data and 6 variables from 12 in the UFO_sightings data. All excluded columns were weather, geotag, shape, and location variables that weren't necessary to answer questions about paranormal sighting by region, season, and type overall . I added an I.D. variable for each state for visualization and dplyr purposes later.  Additionally, longitude and latitudes needed to be coerced into numeric variables to allow for appropriate dplyr shenanigans. I performed a full join of the altered data, which might be cheating. 


####  Wrangling

```{R}
library(lubridate)
date_new <- as.Date(paste(big_clean_UFO$date,"-01",sep=""))
big_clean_UFO %>% 
  mutate(season = lubridate::quarter(date)) %>% 
  mutate(season = case_when(
    season == 1 ~ 'Winter',
    season == 2 ~ 'Spring',
    season == 3 ~ 'Summer',
    season == 4 ~ 'Fall'
  )) %>% 
  separate(date, into=c("year", "month", "day")) %>% 
  select(-c("year", "day", "city"))->big_clean_UFO
big_clean_UFO %>% 
  group_by(state, season, paratype) %>% 
  summarise(mean_lo=mean(longitude),sd_lo=sd(longitude), mean_la=mean(latitude), sd_la=sd(latitude),var_lola=var(longitude, latitude, na.rm = T), max_lo=max(longitude), max_la=max(latitude), min_lo=min(longitude), min_la=min(latitude))

big_clean_UFO %>% 
  group_by(state, ID, paratype, season) %>% 
  summarise(n=n()) %>% 
  arrange(desc(n))->tired

big_clean_UFO %>% 
  filter(season=="Winter") %>% 
  stringr::str_count("cold")
  

```
To better understand circumstances when and where paranormal sightings generally occur, I created a seasons column using mutate(), before removing the year/day/city using separate() and select(). I grouped by paratype, state, and season before generating summary statistic for longitude, latitude. Unfortunately, this information wasn't vary enlightening in isolation. 

The next chunk was an attempt to contextualize previous numeric summary using the season, state, and paratype character variable in the cleaned data. After using trusty group_by() for state and ID I summarized the number sighting occured in each state, before arranging the results in descending order. 

My last chunck was really just a points grab. I filtered rows by season (winter) and then used str_count to determine how many times observations contained the word "cold". Nine times, which is clearly suspicious. 
=======
library(plyr)

big_foot_clean %>% 
  full_join(UFO_sightings_clean, by=c("latitude"="city_latitude", "longitude"="city_longitude", "state"="state", "paratype"="paratype", "date"="date", "observed"="summary"))->big_clean_UFO
```


```{R}
library(tidyverse)
library(stringr)
big_clean_UFO %>% 
  group_by(state) %>% 
  summarise(mean.lat=mean(latitude),mean.long=mean(longitude),var.lat=var(latitude), var.long= var(longitude), na.rm=F)->dply.stats
  
big_clean_UFO %>% 
  filter(state==c("New York", "NY")) %>% 
  mutate(state=str_replace(state, "New York", "NY"))->big_clean_UFO_NY

```
I 
>>>>>>> a8287905c51e6e169e7367ad521a171e2077fad4


#### Visualizing

```{R}
<<<<<<< HEAD
library(RColorBrewer)
ggplot(big_clean_UFO, aes(longitude, latitude))+
  geom_density2d_filled()+
  geom_jitter(aes(colour=paratype))+
  scale_fill_brewer(palette = "Oranges")+
  labs(title="Paranormal Sighting Density: Longitude vs Latitude",x="Longitude", y = "Latitude")
```

This plot considers the probability of of bigfoot and UFO sightings across differing latitudes and longitudes. Vaguely U.S. shaped, it is clear that there is a higher occurrence of bigfoot sightings in the northeast---specifically around Ohio, which is consistent with summary statistic collected in the Wrangling section. UFO sight are more widely dispersed. Behold, it's beauty!
=======
install.packages("usmap")
install.packages("rgdal")
library(usmap)
big_clean_UFO %>% 
  select(longitude, latitude, "paratype")->please.work
  para_map <- usmap_transform(please.work)
plot_usmap() +
  geom_point(data = para_map, aes(x = longitude.1, y = latitude.1, color= paratype), alpha = 0.25)

```

The plot above was supposed to show the paranormal sightings across the United States and to clearly see the distinctly of incidence in particular regions. 
>>>>>>> a8287905c51e6e169e7367ad521a171e2077fad4

```{R}
library(RColorBrewer)

ggplot(big_clean_UFO, aes(x=ID, fill= paratype)) +
  geom_density(alpha=.75)+
  facet_grid(paratype~., scales = "free_y")+
  scale_fill_brewer(palette = "Oranges")+
  labs(title="Density of Paranormal Sightings Across States",x="State I.D.", y = "Density")
  


```

This plot display the density of sightings across states in accordance with numeric State I.D. assigned to data. It is a closer view of the distribution of sightings, which reiterates the the conclusion from the first plot.

```{R}
library(RColorBrewer)
library(ggplot2)
ggplot(big_clean_UFO, aes(x = paratype, fill=season))+ geom_bar(position="fill") +
  scale_fill_brewer(palette = "Oranges")+  
  scale_y_continuous(name = "Density",limits=(c(0,1.1)))+
 labs(title="Paranormal Sightings by Season",x="Paratype", y = "Density")



```

The final bar plot shows a breakdown of sightings according to season and paratype. Interestingly, there appears to be a seasonal fluctuation of UFO sighting according to season that is absent of the bigfoot folks. 

#### Concluding Remarks

What is going on in Ohio? 




